name: "Rust tests"

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "nightly"
          components: "clippy"
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - name: Run checks
        run: cargo hack clippy --feature-powerset --no-dev-deps -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo hack test --feature-powerset

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "nightly"
          components: "miri"
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - name: Run tests through miri
        env:
          RUSTFLAGS: "-Z randomize-layout"
        run: cargo hack miri test --feature-powerset

  address-sanitizer:
    name: Address sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "nightly"
          components: "rust-src"
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - name: Run tests through address sanitizer
        env:
          RUSTFLAGS: "-Z randomize-layout"
        run: cargo hack test --feature-powerset -Zbuild-std --target x86_64-unknown-linux-gnu
